"""
SpecterOSINT - DNS Brute Force Collector
Fuerza bruta de subdominios comunes contra un dominio base.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

import dns.asyncresolver
from specter.collectors.base import BaseCollector
from specter.osint_core.models import (
    CollectorResult,
    EntityNode,
    EntityType,
    RelationEdge,
    RelationType,
)

logger = logging.getLogger("specter.collectors.dns_bruteforce")

_CONCURRENCY = 20

# Lista curada de subdominios comunes
_COMMON_SUBDOMAINS: tuple[str, ...] = (
    "www",
    "mail",
    "ftp",
    "smtp",
    "pop",
    "ns1",
    "ns2",
    "webmail",
    "email",
    "blog",
    "forum",
    "shop",
    "api",
    "dev",
    "test",
    "staging",
    "admin",
    "portal",
    "vpn",
    "remote",
    "secure",
    "owa",
    "autodiscover",
    "lyncdiscover",
    "meet",
    "sip",
    "xmpp",
    "chat",
    "status",
    "monitor",
    "git",
    "svn",
    "cpanel",
    "whm",
    "webdisk",
    "ns3",
    "ns4",
    "static",
    "media",
    "images",
    "img",
    "css",
    "js",
    "assets",
    "cdn",
    "cache",
    "proxy",
    "loadbalancer",
    "firewall",
    "router",
    "switch",
    "printer",
    "camera",
    "phone",
    "voip",
    "pbx",
    "fax",
    "scanner",
    "backup",
    "archive",
    "old",
    "new",
    "beta",
    "alpha",
    "demo",
    "sandbox",
    "lab",
    "research",
    "development",
    "production",
    "staging2",
    "testing",
    "quality",
    "assurance",
    "security",
    "compliance",
    "legal",
    "hr",
    "finance",
    "accounting",
    "sales",
    "marketing",
    "support",
    "help",
    "info",
    "contact",
    "about",
    "jobs",
    "careers",
    "press",
    "news",
    "events",
    "calendar",
    "docs",
    "wiki",
    "kb",
    "knowledge",
    "faq",
    "helpdesk",
    "ticket",
    "issue",
    "bug",
    "feature",
    "request",
    "feedback",
    "survey",
    "poll",
    "vote",
    "rating",
    "review",
    "comment",
    "discussion",
    "community",
    "social",
    "network",
    "share",
    "upload",
    "download",
    "file",
    "storage",
    "drive",
    "aws",
    "azure",
    "gcp",
    "digitalocean",
    "linode",
    "vultr",
    "heroku",
    "netlify",
    "vercel",
    "firebase",
    "cloudflare",
    "akamai",
    "fastly",
    "cloudfront",
    "route53",
    "elb",
    "alb",
    "nlb",
    "waf",
    "ddos",
    "protection",
    "mitigation",
    "prevention",
    "detection",
    "response",
    "recovery",
    "disaster",
    "business",
    "continuity",
    "plan",
    "policy",
    "procedure",
    "guideline",
    "standard",
    "regulation",
    "audit",
    "assessment",
    "certification",
    "accreditation",
    "license",
    "permit",
    "registration",
    "filing",
    "record",
    "document",
    "report",
    "log",
    "trace",
    "track",
    "alert",
    "notification",
    "warning",
    "error",
    "exception",
    "incident",
    "breach",
    "attack",
    "threat",
    "vulnerability",
    "risk",
    "exposure",
    "impact",
    "likelihood",
    "severity",
    "priority",
    "critical",
    "high",
    "medium",
    "low",
    "debug",
    "fatal",
    "panic",
    "crash",
    "failure",
    "success",
    "complete",
    "pending",
    "blocked",
    "cancelled",
    "deferred",
    "postponed",
    "scheduled",
    "planned",
    "estimated",
    "actual",
    "forecast",
    "budget",
    "cost",
    "expense",
    "revenue",
    "profit",
    "loss",
    "margin",
    "growth",
    "decline",
    "trend",
    "pattern",
    "anomaly",
    "outlier",
    "baseline",
    "threshold",
    "limit",
    "cap",
    "floor",
    "ceiling",
    "target",
    "goal",
    "objective",
    "kpi",
    "metric",
    "measure",
    "indicator",
    "benchmark",
    "best",
    "practice",
    "recommendation",
    "suggestion",
    "advice",
    "tip",
    "trick",
    "hack",
    "workaround",
    "fix",
    "patch",
    "update",
    "upgrade",
    "migration",
    "deployment",
    "release",
    "version",
    "build",
    "integration",
    "acceptance",
    "performance",
    "load",
    "stress",
    "soak",
    "spike",
    "endurance",
    "scalability",
    "reliability",
    "availability",
    "durability",
    "consistency",
    "partition",
    "tolerance",
    "isolation",
    "replication",
    "sharding",
    "clustering",
    "federation",
    "distribution",
    "decentralization",
    "centralization",
    "consolidation",
    "virtualization",
    "containerization",
    "orchestration",
    "automation",
    "provisioning",
    "configuration",
    "management",
    "monitoring",
    "logging",
    "tracing",
    "debugging",
    "profiling",
    "optimization",
    "tuning",
    "caching",
    "indexing",
    "partitioning",
    "compression",
    "encryption",
    "decryption",
    "authentication",
    "authorization",
    "accounting",
    "auditing",
    "compliance",
    "governance",
    "risk",
    "management",
    "framework",
    "model",
    "architecture",
    "design",
    "pattern",
    "principle",
    "methodology",
    "approach",
    "strategy",
    "tactic",
    "roadmap",
    "milestone",
    "deliverable",
    "outcome",
    "output",
    "input",
    "throughput",
    "latency",
    "bandwidth",
    "capacity",
    "utilization",
    "efficiency",
    "effectiveness",
    "productivity",
    "quality",
    "satisfaction",
    "engagement",
    "retention",
    "churn",
    "acquisition",
    "conversion",
    "funnel",
    "journey",
    "experience",
    "interface",
    "interaction",
    "usability",
    "accessibility",
    "inclusivity",
    "diversity",
    "equity",
    "belonging",
    "culture",
    "values",
    "mission",
    "vision",
    "purpose",
    "operation",
    "execution",
    "implementation",
    "delivery",
    "maintenance",
    "enhancement",
    "innovation",
    "transformation",
    "disruption",
    "evolution",
    "revolution",
    "paradigm",
    "shift",
    "change",
    "adaptation",
    "resilience",
    "agility",
    "flexibility",
    "privacy",
    "ethics",
    "sustainability",
    "responsibility",
    "accountability",
    "transparency",
    "integrity",
    "trust",
    "confidence",
    "reputation",
    "brand",
    "identity",
    "image",
    "perception",
    "awareness",
    "recognition",
    "loyalty",
    "advocacy",
    "ambassadorship",
    "partnership",
    "collaboration",
    "cooperation",
    "coordination",
    "communication",
    "relationship",
    "ecosystem",
    "platform",
    "marketplace",
    "exchange",
    "transaction",
    "connection",
    "link",
    "bond",
    "tie",
    "association",
    "affiliation",
    "alliance",
    "coalition",
    "integration",
    "merger",
    "acquisition",
    "divestiture",
    "spinoff",
    "joint",
    "venture",
    "strategic",
    "licensing",
    "franchising",
    "distribution",
    "reseller",
    "channel",
    "affiliate",
    "referral",
    "influencer",
    "ambassador",
    "advocate",
    "champion",
    "supporter",
    "follower",
    "fan",
    "customer",
    "client",
    "user",
    "consumer",
    "buyer",
    "seller",
    "vendor",
    "supplier",
    "stakeholder",
    "shareholder",
    "investor",
    "regulator",
    "competitor",
    "peer",
    "colleague",
    "teammate",
    "contributor",
    "maintainer",
    "developer",
    "designer",
    "architect",
    "engineer",
    "analyst",
    "manager",
    "director",
    "executive",
    "leader",
    "founder",
    "owner",
    "creator",
    "maker",
    "builder",
    "innovator",
    "disruptor",
    "pioneer",
    "visionary",
    "strategist",
    "tactician",
    "operator",
    "executor",
    "implementer",
    "deployer",
    "deliverer",
    "enhancer",
    "transformer",
    "evolver",
    "revolutionary",
    "shifter",
    "changer",
    "adapter",
)


async def _resolve_subdomain(
    resolver: dns.asyncresolver.Resolver,
    subdomain: str,
    domain: str,
    semaphore: asyncio.Semaphore,
) -> tuple[str, bool, list[str]]:
    """Resuelve un subdominio. Retorna (subdominio, existe, ips)."""
    fqdn = f"{subdomain}.{domain}"
    async with semaphore:
        try:
            answer = await resolver.resolve(fqdn, "A")
            ips = [str(rdata) for rdata in answer]
            return fqdn, True, ips
        except Exception:
            return fqdn, False, []


class DNSBruteForceCollector(BaseCollector):
    """Fuerza bruta de subdominios comunes contra un dominio base.

    Prueba una lista de subdominios comunes resolviendo DNS para cada uno,
    identificando cuáles existen y a qué IPs resuelven.
    """

    def __init__(self) -> None:
        super().__init__(name="dns_bruteforce")

    async def collect(self, target: str, **kwargs: Any) -> CollectorResult:
        domain = target.strip().lower().rstrip(".")
        wordlist: tuple[str, ...] = tuple(kwargs.get("wordlist", _COMMON_SUBDOMAINS))

        entities: list[EntityNode] = []
        relations: list[RelationEdge] = []
        found_subdomains: list[dict[str, Any]] = []

        # Nodo raíz del dominio
        root = EntityNode.create(
            EntityType.DOMAIN,
            domain,
            f"Dominio: {domain}",
            attributes={"source": "dns_bruteforce"},
        )
        entities.append(root)

        # Resolver asíncrono
        resolver = dns.asyncresolver.Resolver()
        resolver.timeout = 5.0
        resolver.lifetime = 5.0

        semaphore = asyncio.Semaphore(_CONCURRENCY)

        # Ejecutar resoluciones concurrentes
        tasks = [_resolve_subdomain(resolver, sub, domain, semaphore) for sub in wordlist]
        results = await asyncio.gather(*tasks)

        for fqdn, exists, ips in results:
            if exists:
                # Crear entidad SUBDOMAIN
                sub_node = EntityNode.create(
                    EntityType.SUBDOMAIN,
                    fqdn,
                    f"Subdominio: {fqdn}",
                    attributes={
                        "source": "dns_bruteforce",
                        "ips": ips,
                    },
                    confidence=0.9,
                )
                entities.append(sub_node)
                relations.append(
                    RelationEdge(
                        source_id=sub_node.id,
                        target_id=root.id,
                        relation_type=RelationType.SUBDOMAIN_OF,
                    )
                )

                # Crear entidades IP_ADDRESS
                for ip in ips:
                    ip_node = EntityNode.create(
                        EntityType.IP_ADDRESS,
                        ip,
                        f"IP: {ip}",
                        attributes={
                            "source": "dns_bruteforce",
                            "subdomain": fqdn,
                        },
                        confidence=0.8,
                    )
                    entities.append(ip_node)
                    relations.append(
                        RelationEdge(
                            source_id=sub_node.id,
                            target_id=ip_node.id,
                            relation_type=RelationType.RESOLVES_TO,
                        )
                    )

                found_subdomains.append(
                    {
                        "subdomain": fqdn,
                        "ips": ips,
                    }
                )

        metadata: dict[str, Any] = {
            "ok": True,
            "domain": domain,
            "wordlist_size": len(wordlist),
            "subdomains_found": len(found_subdomains),
            "concurrency": _CONCURRENCY,
        }

        return CollectorResult(
            collector_name=self.name,
            source_target=target,
            entities=entities,
            relations=relations,
            raw_payload=json.dumps(
                {
                    "domain": domain,
                    "wordlist_size": len(wordlist),
                    "found": found_subdomains,
                },
                ensure_ascii=False,
            ),
            metadata=metadata,
        )
